apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-array-results
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: array-results
              type: array
              description: The array results
          steps:
            - name: write-array
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "[\"1\",\"2\",\"3\"]" | tee $(results.array-results.path)
      - name: task2
        params:
          - name: foo
            value: "$(tasks.task1.results.array-results[*])"
          - name: bar
            value: "$(tasks.task1.results.array-results[2])"
        taskSpec:
          params:
            - name: foo
              type: array
              default:
                - "defaultparam1"
                - "defaultparam2"
            - name: bar
              type: string
              default: "defaultparam1"
          steps:
            - name: print-foo
              image: bash:latest
              args: [
                "echo",
                "$(params.foo[*])"
              ]
            - name: print-bar
              image: ubuntu
              script: |
                #!/bin/bash
                VALUE=$(params.bar)
                EXPECTED=3
                diff=$(diff <(printf "%s\n" "${VALUE[@]}") <(printf "%s\n" "${EXPECTED[@]}"))
                if [[ -z "$diff" ]]; then
                    echo "Get expected: ${VALUE}"
                    exit 0
                else
                    echo "Want: ${EXPECTED} Got: ${VALUE}"
                    exit 1
                fi
