apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-array-indexing-results
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: array-results
              type: array
              description: The array results
          steps:
            - name: write-array
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "[\"1\",\"2\",\"3\"]" | tee $(results.array-results.path)
      - name: task2
        taskSpec:
          results:
            - name: array-results
              type: array
              description: The array results
          steps:
            - name: write-array
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo -n "[\"4\",\"5\",\"6\"]" | tee $(results.array-results.path)
    results:
      - name: echo-indexing-array-results
        type: string
        description: array element
        value: $(tasks.task1.results.array-results[1])
      - name: echo-array-results
        type: array
        description: whole array
        value: $(tasks.task2.results.array-results[*])
