apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-resolver-
spec:
  workspaces:
    - name: output
      emptyDir: {}
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: path
      value: ./foo.txt
    - name: contents
      value: "hello world"
  taskRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/tektoncd/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /task/write-file/0.1/write-file.yaml
