apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: any-operator-pr-
spec:
  taskRunTemplate:
    serviceAccountName: 'default'
  pipelineSpec:
    params:
      - name: path
        type: string
        description: The path of the file to be created
      - name: branch
        type: string
        description: The list of branch names
    tasks:
      - name: install-dependency
        when:
          - cel: "\"$(params.path)\" != \"\" || \"$(params.branch)\" != \"\""
        taskSpec:
          steps:
            - name: install
              image: ubuntu
              script: 'echo "any"'
      - name: app1
        when:
          - cel: "\"$(params.path)\" != \"\""
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: 'echo "app1"'
      - name: app2
        when:
          - cel: "\"$(params.branch)\" != \"\""
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: 'echo "app2"'
  params:
    - name: path
      value: "path"
    - name: branch
      value: ""
